# Caching section partially sourced from https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/

name: ci
on: [push, pull_request]
jobs:
  ci-backend:
    name: Unit test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        id: cache-backend-node
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules
          key: backend-node-modules-${{ hashFiles('./backend/package-lock.json') }}

      - name: Install
        if: steps.cache-backend-node.outputs.cache-hit == 'false'
        working-directory: ./backend
        run: npm ci
      - name: Test
        run: npm test
        working-directory: ./backend
